import type { Box, FOLD } from "rabbit-ear/types.js";
import { includeS } from "rabbit-ear/math/compare.js";
import { intersectLineLine } from "rabbit-ear/math/intersect.js";
import { filterKeysWithPrefix, filterKeysWithSuffix, getDimensionQuick } from "rabbit-ear/fold/spec.js";
import { subgraphExclusive } from "rabbit-ear/graph/subgraph.js";
import type { FOLDSelection } from "./selection.ts";

const pointInRect2 = (p: [number, number], rect: Box) =>
  p[0] > rect.min[0] &&
  p[0] < rect.max[0] &&
  p[1] > rect.min[1] &&
  p[1] < rect.max[1];

const pointInRect3 = (p: [number, number, number], rect: Box) =>
  p[0] > rect.min[0] &&
  p[0] < rect.max[0] &&
  p[1] > rect.min[1] &&
  p[1] < rect.max[1] &&
  p[2] > rect.min[2] &&
  p[2] < rect.max[2];

// the largest valid subcomplex generated by a given vertex set
// (all edges/faces whose vertices are fully included).
export const strictSelectComponents = (graph: FOLD, rect: Box): FOLDSelection => {
  const dimension = getDimensionQuick(graph);
  const verticesLookup = dimension === 3
    ? graph.vertices_coords?.map((p) => pointInRect3(p as [number, number, number], rect))
    : graph.vertices_coords?.map((p) => pointInRect2(p as [number, number], rect))
  if (!verticesLookup) { return {}; }
  const vertices = new Set((verticesLookup ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  const edgesLookup = (graph.edges_vertices ?? [])
    .map(vertices => vertices
      .map(v => verticesLookup[v])
      .reduce((a, b) => a && b, true));
  const edges = new Set((edgesLookup ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  const facesLookup = (graph.faces_vertices ?? [])
    .map(vertices => vertices
      .map(v => verticesLookup[v])
      .reduce((a, b) => a && b, true));
  const faces = new Set((facesLookup ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  return { vertices, edges, faces };
};

const closedSubcomplex = (graph: FOLD, selection: FOLDSelection): FOLDSelection => {
  const lookup: {
    vertices: boolean[],
    edges: boolean[],
    faces: boolean[],
  } = { vertices: [], edges: [], faces: [] };
  selection.faces?.forEach((f) => {
    lookup.faces[f] = true;
  });
  if (graph.faces_vertices) {
    selection.faces?.forEach((face) =>
      graph.faces_vertices![face].forEach((v) => {
        lookup.vertices[v] = true;
      }));
  }
  if (graph.faces_edges) {
    selection.faces?.forEach((face) =>
      graph.faces_edges![face].forEach((e) => {
        lookup.edges[e] = true;
      }));
  }

  selection.edges?.forEach((e) => {
    lookup.edges[e] = true;
  });
  if (graph.edges_vertices) {
    selection.edges?.forEach((edge) =>
      graph.edges_vertices![edge]?.forEach((v) => {
        lookup.vertices[v] = true;
      }));
  }

  selection.vertices?.forEach((v) => {
    lookup.vertices[v] = true;
  });

  const vertices = new Set((lookup.vertices ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  const edges = new Set((lookup.edges ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  const faces = new Set((lookup.faces ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  return { vertices, edges, faces };
};

const closedSubgraph = (graph: FOLD, selection: FOLDSelection): FOLDSelection => {
  const lookup: {
    vertices: boolean[],
    edges: boolean[],
  } = { vertices: [], edges: [] };
  selection.edges?.forEach((e) => {
    lookup.edges[e] = true;
  });
  if (graph.edges_vertices) {
    selection.edges?.forEach((edge) =>
      graph.edges_vertices![edge]?.forEach((v) => {
        lookup.vertices[v] = true;
      }));
  }

  selection.vertices?.forEach((v) => {
    lookup.vertices[v] = true;
  });

  const vertices = new Set((lookup.vertices ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  const edges = new Set((lookup.edges ?? [])
    .map((sel, i) => (sel ? i : undefined))
    .filter((a) => a !== undefined));
  return { vertices, edges };
};

export const strictSubcomplex = (graph: FOLD, selection: FOLDSelection): FOLD => {
  const closedSelection = closedSubcomplex(graph, selection);
  return subgraphExclusive(graph, closedSelection);
};

export const strictSubgraph = (graph: FOLD, selection: FOLDSelection): FOLD => {
  const closedSelection = closedSubgraph(graph, selection);
  return subgraphExclusive(graph, closedSelection);
};

export const vertexSubgraph = (graph: FOLD, selection: FOLDSelection): FOLD => {
  const closedSelection = { vertices: selection.vertices ?? [] };
  return subgraphExclusive(graph, closedSelection);
};

